# Generated by Django 4.1.7 on 2023-05-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadhar_number',
            field=models.CharField(max_length=12),
        ),
    ]
