# Generated by Django 4.1.7 on 2023-03-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_patientdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdata',
            old_name='Data',
            new_name='P_data',
        ),
    ]
