# Generated by Django 4.1.7 on 2023-03-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('subject', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='Notification',
            new_name='DoctorNotification',
        ),
    ]
