# Generated by Django 4.1.7 on 2023-03-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_data_patientdata_p_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='P_data',
            field=models.FileField(upload_to=''),
        ),
    ]
