# Generated by Django 4.1.5 on 2023-02-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
