# Generated by Django 4.1.7 on 2023-03-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_patientnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
