# Generated by Django 4.1.7 on 2023-04-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_patientdata_p_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='Title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
